import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { FinancialReportResult } from './report.service.js'

export async function generateReportPdf(report: FinancialReportResult): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

  const A4_W = 595.28
  const A4_H = 841.89
  const MARGIN = 40
  let page = pdfDoc.addPage([A4_W, A4_H])
  let y = A4_H - MARGIN

  const drawText = (
    text: string,
    x: number,
    yPos: number,
    size = 10,
    bold = false,
    color = rgb(0.1, 0.1, 0.1)
  ) => {
    page.drawText(String(text), { x, y: yPos, size, font: bold ? boldFont : regularFont, color })
  }

  // Header
  page.drawRectangle({ x: 0, y: A4_H - 60, width: A4_W, height: 60, color: rgb(0.25, 0.32, 0.71) })
  drawText('FINANCIAL REPORT', MARGIN, A4_H - 35, 16, true, rgb(1, 1, 1))
  drawText(`${report.dateFrom} to ${report.dateTo}`, MARGIN, A4_H - 52, 9, false, rgb(0.85, 0.9, 1))

  y = A4_H - 80

  // Summary box
  const { summary } = report
  const fmt = (n: number) => `${summary.currency} ${n.toFixed(2)}`

  page.drawRectangle({
    x: MARGIN,
    y: y - 110,
    width: A4_W - MARGIN * 2,
    height: 105,
    color: rgb(0.97, 0.97, 0.97),
    borderColor: rgb(0.85, 0.85, 0.85),
    borderWidth: 0.5,
  })

  drawText('SUMMARY', MARGIN + 10, y - 20, 10, true)

  const col1 = MARGIN + 10
  const col2 = A4_W / 2

  drawText(`Generated Revenue:`, col1, y - 38, 9)
  drawText(fmt(summary.totalGeneratedRevenue), col1 + 130, y - 38, 9, true)

  drawText(`Realized Revenue:`, col1, y - 52, 9)
  drawText(fmt(summary.totalRealizedRevenue), col1 + 130, y - 52, 9, true, rgb(0.1, 0.5, 0.1))

  drawText(`Outstanding Revenue:`, col1, y - 66, 9)
  drawText(fmt(summary.totalOutstandingRevenue), col1 + 130, y - 66, 9, true, rgb(0.7, 0.4, 0))

  drawText(`Commission (${(summary.commissionRate * 100).toFixed(0)}%):`, col2, y - 38, 9)
  drawText(fmt(summary.commissionAmount), col2 + 120, y - 38, 9, true, rgb(0.7, 0.2, 0.1))

  drawText(`Net Revenue:`, col2, y - 52, 9)
  drawText(fmt(summary.netRevenue), col2 + 120, y - 52, 9, true, rgb(0.1, 0.5, 0.1))

  drawText(
    `Tokens: ${summary.totalGeneratedTokens} generated / ${summary.totalUsedTokens} used / ${summary.totalUnusedTokens} unused`,
    col1,
    y - 100,
    8,
    false,
    rgb(0.4, 0.4, 0.4)
  )

  y -= 125

  // Table header
  const COL_WIDTHS = [120, 90, 50, 50, 70, 70, 50]
  const COL_HEADERS = ['Branch', 'Plan', 'Gen.', 'Used', 'Realized', 'Outstanding', 'Usage%']
  let xCursor = MARGIN

  page.drawRectangle({
    x: MARGIN,
    y: y - 18,
    width: A4_W - MARGIN * 2,
    height: 18,
    color: rgb(0.9, 0.92, 0.98),
  })
  COL_HEADERS.forEach((h, i) => {
    drawText(h, xCursor + 3, y - 13, 8, true, rgb(0.25, 0.32, 0.71))
    xCursor += COL_WIDTHS[i]
  })
  y -= 22

  // Table rows
  for (const row of report.rows) {
    if (y < MARGIN + 30) {
      page = pdfDoc.addPage([A4_W, A4_H])
      y = A4_H - MARGIN
    }

    xCursor = MARGIN
    const vals = [
      row.branch.slice(0, 18),
      row.planName.slice(0, 14),
      String(row.generatedCount),
      String(row.usedCount),
      `${row.currency} ${row.realizedRevenue.toFixed(2)}`,
      `${row.currency} ${row.outstandingRevenue.toFixed(2)}`,
      `${row.usagePercent}%`,
    ]
    vals.forEach((v, i) => {
      drawText(v, xCursor + 3, y - 10, 7.5)
      xCursor += COL_WIDTHS[i]
    })

    page.drawLine({
      start: { x: MARGIN, y: y - 14 },
      end: { x: A4_W - MARGIN, y: y - 14 },
      thickness: 0.2,
      color: rgb(0.88, 0.88, 0.88),
    })

    y -= 16
  }

  // Footer
  const lastPage = pdfDoc.getPage(pdfDoc.getPageCount() - 1)
  lastPage.drawText(`Generated by NexRAD on ${new Date(report.generatedAt).toLocaleString()}`, {
    x: MARGIN,
    y: 20,
    size: 7,
    font: regularFont,
    color: rgb(0.6, 0.6, 0.6),
  })

  return pdfDoc.save()
}
